font_family Monaco
font_size 13.5

startup_session launch.conf

macos_option_as_alt yes

window_padding_width 0
window_margin_width 0
window_border_width 0
tab_bar_margin_width 0
tab_bar_margin_height 0 0
placement_strategy bottom-left
resize_in_steps yes

#include current-theme.conf
