# special
#foreground		#444444
background		black
#cursor			#af0000
#cursor_text_color	background

# black
color0			#eeeeee
color8			#bcbcbc

# red
color1			#af0000
color9			#d70000

# green
color2      #558b33
color10     #7aba39

# yellow
color3      #f19618
color11     #ffc849

# blue
color4			#0087af
color12			#d75f00

# magenta
color5			#878787
color13			#d75f00

# cyan
color6			#005f87
color14			#3e999f

# white
color7			#444444
color15			#005f87

# 232-255 grayscale
# 233 #000000
# 255 #ffffff

#background            #fafafa
#foreground            #5b6673
#cursor                #ff6900
#selection_background  #f0ede4
#color0                #000000
#color8                #323232
#color1                #ff3333
#color9                #ff6565
#color2                #86b200
#color10               #b8e532
#color3                #f19618
#color11               #ffc849
#color4                #41a6d9
#color12               #73d7ff
#color5                #f07078
#color13               #ffa3aa
#color6                #4cbe99
#color14               #7ff0cb
#color7                #ffffff
#color15               #ffffff
#selection_foreground #fafafa
