local C = require('_.colors.palette')

local M = {}

M.lualine = {
  LualineNormalA = { fg = C.crust, bg = C.blue, bold = true },
  LualineNormalB = { fg = C.text, bg = C.surface0 },
  LualineNormalC = { fg = C.text, bg = C.surface0 },
  LualineNormalMode = { link = 'LualineNormalA' },
  LualineNormalInsert = { fg = C.crust, bg = C.green, bold = true },
  LualineNormalReplace = { fg = C.crust, bg = C.red, bold = true },
  LualineNormalVisual = { fg = C.crust, bg = C.peach, bold = true },
  LualineNormalCommand = { fg = C.crust, bg = C.teal, bold = true },
  LualineNormalInactive = { fg = C.overlay1, bg = C.surface0 },

  LualineInsertA = { link = 'LualineNormalInsert' },
  LualineInsertB = { link = 'LualineNormalB' },
  LualineInsertC = { link = 'LualineNormalC' },
  LualineInsertMode = { link = 'LualineInsertA' },
  LualineInsertReplace = { fg = C.crust, bg = C.peach, bold = true },

  LualineReplaceA = { link = 'LualineNormalReplace' },
  LualineReplaceB = { link = 'LualineNormalB' },
  LualineReplaceC = { link = 'LualineNormalC' },
  LualineReplaceMode = { link = 'LualineReplaceA' },

  LualineVisualA = { link = 'LualineNormalVisual' },
  LualineVisualB = { link = 'LualineNormalB' },
  LualineVisualC = { link = 'LualineNormalC' },
  LualineVisualMode = { link = 'LualineVisualA' },

  LualineCommandA = { link = 'LualineNormalCommand' },
  LualineCommandB = { link = 'LualineNormalB' },
  LualineCommandC = { link = 'LualineNormalC' },

  LualineInactiveA = { link = 'LualineNormalInactive' },
  LualineInactiveB = { link = 'LualineNormalInactive' },
  LualineInactiveC = { link = 'LualineNormalInactive' },

  LualineTabActive = { fg = C.text, bg = C.surface0 },
  LualineTabInactive = { fg = C.overlay1, bg = C.mantle },
  LualineTabSel = { link = 'LualineNormalA' },

  LualineFiletypeA = { link = 'LualineNormalA' },
  LualineFiletypeB = { link = 'LualineNormalB' },
  LualineFiletypeC = { link = 'LualineNormalC' },

  LualineBranchName = { fg = C.mauve },
  LualineGitHubNvimUsername = { link = 'LualineBranchName' },
  LualineHostname = { fg = C.peach },
  LualineScrollBar = { fg = C.overlay1 },
  LualineDiffAdded = { fg = C.green },
  LualineDiffAddedFile = { link = 'LualineDiffAdded' },
  LualineDiffModified = { fg = C.yellow },
  LualineDiffModifiedFile = { link = 'LualineDiffModified' },
  LualineDiffRemoved = { fg = C.red },
  LualineDiffRemovedFile = { link = 'LualineDiffRemoved' },
  LualineDiffUntracked = { fg = C.overlay1 },
  LualineDiffUntrackedFile = { link = 'LualineDiffUntracked' },
}

M.telescope = {
  TelescopeBorder = { fg = C.overlay1 },
  TelescopeNormal = { bg = C.surface0 },
  TelescopePromptNormal = { bg = C.surface0 },
  TelescopePromptTitle = { fg = C.crust, bg = C.peach },
  TelescopeResultsTitle = { fg = C.crust, bg = C.blue },
  TelescopePreviewTitle = { fg = C.crust, bg = C.green },
  TelescopeSelection = { bg = C.surface1 },
  TelescopeSelectionCaret = { fg = C.mauve },
  TelescopeMultiSelection = { bg = C.surface0 },
  TelescopeMultiIcon = { fg = C.mauve },
  TelescopeMatching = { fg = C.teal, bold = true },
  TelescopePromptCounter = { fg = C.mauve },
  TelescopePromptPrefix = { fg = C.mauve },
}

M.nvimtree = {
  NvimTreeNormal = { bg = C.mantle },
  NvimTreeNormalNC = { bg = C.mantle },
  NvimTreeWinSeparator = { link = 'VertSplit' },
  NvimTreeCursorLine = { bg = C.surface0 },
  NvimTreeCursorLineNr = { fg = C.text, bg = C.surface0 },

  NvimTreeFolderName = { fg = C.blue },
  NvimTreeFolderIcon = { fg = C.blue },
  NvimTreeOpenedFolderName = { fg = C.blue },
  NvimTreeEmptyFolderName = { fg = C.blue },

  NvimTreeIndentMarker = { fg = C.overlay1 },
  NvimTreeGitignoreIcon = { fg = C.overlay1 },
  NvimTreeSymlink = { fg = C.sapphire },
  NvimTreeSpecialFile = { fg = C.yellow },

  NvimTreeRootFolder = { fg = C.text, bold = true },

  NvimTreeStatusLineNC = { link = 'StatusLineNC' },
  NvimTreeStatusLine = { link = 'StatusLine' },

  NvimTreeGitDirty = { fg = C.peach },
  NvimTreeGitStaged = { fg = C.green },
  NvimTreeGitMerge = { fg = C.peach },
  NvimTreeGitRenamed = { fg = C.yellow },
  NvimTreeGitNew = { fg = C.green },
  NvimTreeGitDeleted = { fg = C.red },

  NvimTreeLspDiagnosticsError = { link = 'DiagnosticError' },
  NvimTreeLspDiagnosticsWarning = { link = 'DiagnosticWarn' },
  NvimTreeLspDiagnosticsInformation = { link = 'DiagnosticInfo' },
  NvimTreeLspDiagnosticsHint = { link = 'DiagnosticHint' },
}

M.fzf = {
  fzf1 = { fg = C.mauve, bg = C.surface0 },
  fzf2 = { fg = C.text, bg = C.surface0 },
  fzf3 = { fg = C.teal, bg = C.surface0 },
  ['fzfTerminalFace'] = { fg = C.text, bg = C.mantle },
  ['fzfNormal'] = { link = 'TelescopeNormal' },
  ['fzfInfo'] = { fg = C.overlay1 },
  ['fzfPrompt'] = { fg = C.mauve },
  ['fzfKeyword'] = { fg = C.peach },
  ['fzfHeader'] = { fg = C.subtext1 },
  ['fzfSelection'] = { fg = C.crust, bg = C.mauve, bold = true },
  ['fzfSelected'] = { link = 'fzfSelection' },
  ['fzfFgPlus'] = { fg = C.text },
  ['fzfBgPlus'] = { fg = C.surface1 },
  ['fzfFgMinus'] = { fg = C.overlay1 },
  ['fzfBgMinus'] = { fg = C.surface0 },
  ['fzfPreview'] = { fg = C.subtext1 },
}

M.gitsigns = {
  GitSignsAdd = { link = 'DiffAdded' },
  GitSignsAddNr = { link = 'GitSignsAdd' },
  GitSignsAddLn = { link = 'GitSignsAdd' },
  GitSignsChange = { link = 'DiffChanged' },
  GitSignsChangeNr = { link = 'GitSignsChange' },
  GitSignsChangeLn = { link = 'GitSignsChange' },
  GitSignsDelete = { link = 'DiffDeleted' },
  GitSignsDeleteNr = { link = 'GitSignsDelete' },
  GitSignsDeleteLn = { link = 'GitSignsDelete' },
  GitSignsTopdelete = { link = 'GitSignsDelete' },
  GitSignsTopdeleteNr = { link = 'GitSignsDelete' },
  GitSignsTopdeleteLn = { link = 'GitSignsDelete' },
  GitSignsUntracked = { fg = C.overlay1 },
  GitSignsUntrackedNr = { link = 'GitSignsUntracked' },
  GitSignsUntrackedLn = { link = 'GitSignsUntracked' },
}

M.mini = {
  MiniIndentscopeSymbol = { link = 'MiniIndentscopeSymbol' },
  MiniIndentscopeSymbolWin = { link = 'MiniIndentscopeSymbol' },
  MiniJump = { bg = C.surface0, fg = C.mauve },
  MiniJump2dSpot = { fg = C.peach, bold = true, nocombine = true },
  MiniMapCanvasBackground = { bg = C.mantle },
  MiniMapCanvasBottom = { fg = C.overlay1 },
  MiniMapCanvasLeft = { fg = C.overlay1 },
  MiniMapCanvasRight = { fg = C.overlay1 },
  MiniMapCanvasTop = { fg = C.overlay1 },
  MiniMapFooter = { fg = C.overlay1 },
  MiniMapLegendBorder = { fg = C.overlay1 },
  MiniMapLegendNormal = { fg = C.blue },
  MiniMapLegendSymbolInactive = { fg = C.overlay1 },
  MiniMapLegendSymbolNormal = { link = 'MiniMapLegendNormal' },
  MiniMapLegendSymbolShift = { fg = C.red },
  MiniMapSymbolDetail = { fg = C.subtext1 },
  MiniMapSymbolLine = { fg = C.subtext0 },
  MiniMapSymbolView = { fg = C.overlay1 },
  MiniStarterCurrent = { nocombine = true },
  MiniStarterFoot = { fg = C.overlay1 },
  MiniStarterHeader = { fg = C.mauve },
  MiniStarterInactive = { link = 'Comment' },
  MiniStarterQuery = { fg = C.green },
  MiniStarterSection = { fg = C.blue },
  MiniStarterTitle = { fg = C.peach, bold = true },
  MiniStatuslineDevinfo = { link = 'StatusLine' },
  MiniStatuslineFileinfo = { link = 'StatusLine' },
  MiniStatuslineFilename = { link = 'StatusLineFilename' },
  MiniStatuslineModeCommand = { link = 'LualineNormalCommand' },
  MiniStatuslineModeInsert = { link = 'LualineNormalInsert' },
  MiniStatuslineModeNormal = { link = 'LualineNormalA' },
  MiniStatuslineModeReplace = { link = 'LualineNormalReplace' },
  MiniStatuslineModeVisual = { link = 'LualineNormalVisual' },
  MiniSurroundBorder = { fg = C.peach, bold = true },
  MiniTablineCurrent = { link = 'TabLineSel' },
  MiniTablineFill = { link = 'TabLineFill' },
  MiniTablineHidden = { link = 'TabLine' },
  MiniTablineInactive = { link = 'TabLine' },
  MiniTablineModifierSelected = { link = 'MiniTablineCurrent' },
  MiniTablineVisibleCurrent = { link = 'MiniTablineCurrent' },
  MiniTablineVisibleHidden = { link = 'MiniTablineHidden' },
  MiniTablineVisibleInactive = { link = 'MiniTablineInactive' },
  MiniTestEmphasis = { bold = true },
  MiniTestFail = { fg = C.red, bold = true },
  MiniTestPassed = { fg = C.green, bold = true },
  MiniTrailspace = { bg = C.red },
}

M.noice = {
  NoiceCmdlineIcon = { fg = C.subtext1 },
  NoiceCmdlineIconBorder = { fg = C.subtext1 },
  NoiceCmdlinePopup = { bg = C.surface0 },
  NoiceCmdlinePopupBorder = { fg = C.overlay1 },
  NoiceCmdlinePopupBorderError = { fg = C.red },
  NoiceCmdlinePopupBorderWarn = { fg = C.yellow },
  NoiceCmdlinePopupTitle = { fg = C.text, bold = true },
  NoiceConfirmBorder = { fg = C.blue },
  NoiceFormatConfirm = { fg = C.text },
  NoiceFormatConfirmButton = { fg = C.mauve },
  NoiceFormatDoc = { fg = C.text },
  NoiceFormatTitle = { fg = C.peach, bold = true },
  NoiceFormatKind = { fg = C.mauve },
  NoiceFormatKindCommand = { link = 'NoiceFormatKind' },
  NoiceFormatKindFilter = { link = 'NoiceFormatKind' },
  NoiceFormatKindHistory = { link = 'NoiceFormatKind' },
  NoiceFormatKindPicker = { link = 'NoiceFormatKind' },
  NoiceFormatLspProgress = { fg = C.text },
  NoiceFormatLspProgressClient = { fg = C.teal },
  NoiceFormatLspProgressSpinner = { fg = C.peach },
  NoiceFormatLspQuickfix = { fg = C.text },
  NoiceFormatLspReport = { fg = C.subtext1 },
  NoiceFormatSignal = { fg = C.overlay1 },
  NoiceFormatSource = { fg = C.overlay1 },
  NoiceFormatWaveform = { fg = C.blue },
  NoiceFormatWizard = { fg = C.text },
  NoiceHoverBorder = { fg = C.teal },
  NoiceLspProgressBar = { bg = C.surface0, fg = C.teal },
  NoiceLspProgressBarError = { bg = C.surface0, fg = C.red },
  NoiceLspProgressBarWarn = { bg = C.surface0, fg = C.yellow },
  NoicePopupBorder = { link = 'NoiceCmdlinePopupBorder' },
  NoicePopupmenu = { link = 'Pmenu' },
  NoicePopupmenuBorder = { link = 'NoiceCmdlinePopupBorder' },
  NoicePopupmenuFiltered = { fg = C.overlay1 },
  NoicePopupmenuMatch = { link = 'TelescopeMatching' },
  NoicePopupmenuSelected = { link = 'PmenuSel' },
  NoiceScrollbar = { link = 'PmenuThumb' },
  NoiceScrollbarThumb = { link = 'PmenuThumb' },
}

M.flutter = {
  FlutterWidgetCode = { fg = C.text },
  FlutterWidgetGuides = { fg = C.overlay1 },
  FlutterWidgetStructure = { fg = C.mauve },
  FlutterToolsScreen = { link = 'Normal' },
}

M.dap = {
  DapUIPlayPause = { fg = C.green },
  DapUIRestart = { fg = C.green },
  DapUIStop = { fg = C.red },
  DapUIBreakpointsInfo = { fg = C.peach },
  DapUIBreakpointsPath = { fg = C.blue },
  DapUIBreakpointsStoppedPath = { link = 'DapUIBreakpointsPath' },
  DapUICurrentFrame = { bg = C.surface0 },
  DapUIEndOfBuffer = { fg = C.overlay1 },
  DapUIFloatBorder = { fg = C.teal },
  DapUILineNumber = { fg = C.mauve },
  DapUIModifiedValue = { fg = C.peach, bold = true },
  DapUINormalFloat = { bg = C.surface0 },
  DapUIRename = { fg = C.blue },
  DapUIScope = { fg = C.blue },
  DapUISource = { fg = C.mauve },
  DapUIStepBack = { fg = C.subtext1 },
  DapUIStepInto = { fg = C.subtext1 },
  DapUIStepOver = { fg = C.subtext1 },
  DapUIThread = { fg = C.green },
  DapUIType = { fg = C.teal },
  DapUIUnavailable = { fg = C.overlay1 },
  DapUIWatchesEmpty = { fg = C.overlay1 },
  DapUIWatchesError = { fg = C.red },
  DapUIWatchesValue = { fg = C.text },
  DapUIWatchesSelected = { fg = C.blue },
}

M.alpha = {
  AlphaButtons = { fg = C.blue },
  AlphaFooter = { fg = C.overlay1 },
  AlphaHeader = { fg = C.mauve },
  AlphaLeader = { fg = C.mauve },
  AlphaShortcut = { fg = C.peach },
}

M.headlines = {
  Headline1 = { fg = C.mauve, bg = C.mantle, bold = true },
  Headline2 = { fg = C.blue, bg = C.mantle, bold = true },
  Headline3 = { fg = C.green, bg = C.mantle, bold = true },
  Headline4 = { fg = C.yellow, bg = C.mantle },
  Headline5 = { fg = C.peach, bg = C.mantle },
  Headline6 = { fg = C.rosewater, bg = C.mantle },
  Dash = { fg = C.overlay1 },
  CodeBlock = { fg = C.text },
  Quote = { fg = C.overlay1 },
}

M.navic = {
  NavicIconsBoolean = { link = 'Boolean' },
  NavicIconsClass = { link = 'Class' },
  NavicIconsConstant = { link = 'Constant' },
  NavicIconsConstructor = { link = 'Type' },
  NavicIconsDefault = { fg = C.text },
  NavicIconsEnum = { link = 'Enum' },
  NavicIconsEnumMember = { link = 'EnumMember' },
  NavicIconsEvent = { fg = C.peach },
  NavicIconsField = { link = 'Field' },
  NavicIconsFile = { fg = C.text },
  NavicIconsFunction = { link = 'Function' },
  NavicIconsInterface = { fg = C.yellow },
  NavicIconsKey = { fg = C.mauve },
  NavicIconsKeyword = { link = 'Keyword' },
  NavicIconsMethod = { link = 'Method' },
  NavicIconsModule = { link = 'Namespace' },
  NavicIconsNamespace = { link = 'Namespace' },
  NavicIconsNull = { fg = C.mauve },
  NavicIconsNumber = { link = 'Number' },
  NavicIconsObject = { fg = C.yellow },
  NavicIconsOperator = { link = 'Operator' },
  NavicIconsPackage = { fg = C.text },
  NavicIconsProperty = { link = 'Property' },
  NavicIconsReference = { fg = C.text },
  NavicIconsSnippet = { fg = C.peach },
  NavicIconsString = { link = 'String' },
  NavicIconsStruct = { link = 'Structure' },
  NavicIconsText = { fg = C.text },
  NavicIconsType = { link = 'Type' },
  NavicIconsTypeParameter = { fg = C.sapphire },
  NavicIconsVariable = { link = 'Variable' },
  NavicSeparator = { fg = C.subtext1 },
  NavicText = { fg = C.text },
}

return M
