#!/usr/bin/env sh

# https://github.com/kevva/pid-from-port/blob/master/index.js

QUERY=$1
TOP=10

write_alfred_empty_list() {
  local message=$1

  echo '{"items": ['
  echo "{"
  echo "  \"uid\": \"empty\","
  echo "  \"title\": \"$message\","
  echo "}"
  echo ']}'
}

list_by_id() {
  local list=$(grep_id $1 | sort -nr)

  if [[ ! -z "$list" ]]; then
    echo '{"items": ['
    echo "$list" | while read cpu pid;
    do
      local name=$(ps -p $pid -c -o command=)
      #local bin=$(lsof -p $pid | tr -s ' ' | grep ' txt ' | grep "/$name" | cut -d ' ' -f 9-)
      #local comm=$(ps -p $pid -o comm=)
      local command=$(ps -p $pid -o command=)
      #local len=$(echo $comm | wc -c)
      #local args=$(echo $command | cut -c $len-)

      local uid=$pid
      local title=$name
      local subtitle="$cpu%"
      local arg=$pid

      if [[ $name == "node" ]]; then
        title="node @ $(${bin} --version)"
      fi

      echo "{"
      echo "  \"uid\": \"$pid\","
      echo "  \"title\": \"$title\","
      echo "  \"subtitle\": \"$subtitle\","
      echo "  \"arg\": \"$arg\","
      echo "  \"mods\": {"
      echo "    \"cmd\": {"
      echo "      \"subtitle\": \"Copy pid $pid to clipboard\""
      echo "    },"
      echo "    \"alt\": {"
      echo "      \"subtitle\": \"$subtitle\""
      echo "    }"
      echo "  },"
      #echo '        "autocomplete": "Desktop",'
      echo " \"icon\": {"
      echo "   \"type\": \"\","
      echo "   \"path\": \"/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/ExecutableBinaryIcon.icns\""
      echo " }"
      echo "}"
    done
    echo ']}'
  else
    write_alfred_empty_list "No process found by id: $1"
  fi
}

# FIXME how to handle process can open multiple ports?
list_by_port() {
  local list=$(grep_port $1 | sort -n -k1,1r -k2,2)

  if [[ ! -z "$list" ]]; then
    echo '{"items": ['
    echo "$list" | while read cpu pid port;
    do
      local name=$(ps -p $pid -c -o command=)
      #local bin=$(lsof -p $pid | tr -s ' ' | grep ' txt ' | grep "/$name" | cut -d ' ' -f 9-)
      #local comm=$(ps -p $pid -o comm= -o command=)
      local command=$(ps -p $pid -o command=)
      #local len=$(echo $comm | wc -c)
      #local args=$(echo $command | cut -c $len-)

      local uid=$pid
      local title=$name
      local subtitle="$cpu% CPU @ $command"
      local arg=$pid

      #if [[ $name == "node" ]]; then
      #  title="node @ $(${bin} --version)"
      #fi

      title="$title (:$port)"

      echo "{"
      echo "  \"uid\": \"$uid\","
      echo "  \"title\": \"$title\","
      echo "  \"subtitle\": \"$subtitle\","
      echo "  \"arg\": \"$arg\","
      echo "  \"mods\": {"
      echo "    \"cmd\": {"
      echo "      \"subtitle\": \"Copy pid $pid to clipboard\""
      echo "    },"
      echo "    \"alt\": {"
      echo "      \"subtitle\": \"$command\""
      echo "    }"
      echo "  },"
      #echo '        "autocomplete": "Desktop",'
      echo " \"icon\": {"
      echo "   \"type\": \"\","
      echo "   \"path\": \"/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/ExecutableBinaryIcon.icns\""
      echo " }"
      echo "}"
    done
    echo ']}'
  else
    write_alfred_empty_list "No process found on port: $1"
  fi
}

list_by_name() {
  local list=$(grep_name $1 | sort -n -k1,1r -k2,2)

  if [[ ! -z "$list" ]]; then
    local first=""

    echo '{"items": ['
    echo "$list" | while read cpu pid;
    do
      local name=$(ps -p $pid -c -o command=)
      #local bin=$(lsof -p $pid | tr -s ' ' | grep ' txt ' | grep "/$name" | cut -d ' ' -f 9-)
      local command=$(ps -p $pid -o command=)

      local uid=$pid
      local title=$name
      local subtitle="$cpu% CPU @ $command"
      local arg=$pid

      #if [[ $name == "node" ]]; then
      #  local comm=$(ps -p $pid -o comm=)
      #  local len=$(echo $comm | wc -c)
      #  local args=$(echo $command | cut -c $len-)
      #  echo $args
      #  local script=$(basename $args)

      #  echo $script
      ##  local version=$(${bin} --version);
      ##  echo $comm $bin
      ##  title="node @ $version"
      #fi

      if [[ -z "$first" ]];
      then
        first="true"
      else
        echo ","
      fi

      echo "{"
      echo "  \"uid\": \"$uid\","
      echo "  \"title\": \"$title\","
      echo "  \"subtitle\": \"$subtitle\","
      echo "  \"arg\": \"$arg\","
      echo "  \"mods\": {"
      echo "    \"cmd\": {"
      echo "      \"subtitle\": \"Copy pid $pid to clipboard\""
      echo "    },"
      echo "    \"alt\": {"
      echo "      \"subtitle\": \"$subtitle\""
      echo "    }"
      echo "  },"
      #echo '        "autocomplete": "Desktop",'
      echo " \"icon\": {"
      echo "   \"type\": \"\","
      echo "   \"path\": \"/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/ExecutableBinaryIcon.icns\""
      echo " }"
      echo "}"
    done
    echo ']}'
  else
    write_alfred_empty_list "No process found with name: $1"
  fi
}

list_by_port_usage() {
  local list=$(netstat -anv | grep 'LISTEN' | tr -s ' ' | cut -d ' ' -f 4,9 | cut -d '.' -f 2 | uniq)
  local first=""

  echo '{"items": ['
  echo "$list" | while read port pid;
  do
    local cpu=$(ps -p $pid -o %cpu=)
    local name=$(ps -p $pid -c -o command=)
    #local bin=$(lsof -p $pid | tr -s ' ' | grep ' txt ' | grep "/$name" | cut -d ' ' -f 9-)
    #local comm=$(ps -p $pid -o comm=)
    local command=$(ps -p $pid -o command=)
    #local len=$(echo $comm | wc -c)
    #local args=$(echo $command | cut -c $len-)

    local uid=$pid
    local title=$name
    local subtitle="$cpu% CPU @ $command"

    if [[ -z "$first" ]];
    then
      first="true"
    else
      echo ","
    fi

    echo "{"
    echo "  \"uid\": \"$uid\","
    echo "  \"title\": \"$title\","
    echo "  \"subtitle\": \"$subtitle\","
    echo "  \"arg\": \"$arg\","
    echo "  \"mods\": {"
    echo "    \"cmd\": {"
    echo "      \"subtitle\": \"Copy pid $pid to clipboard\""
    echo "    },"
    echo "    \"alt\": {"
    echo "      \"subtitle\": \"$subtitle\""
    echo "    }"
    echo "  }"
    #echo '        "autocomplete": "Desktop",'
    #echo '        "icon": {'
    #echo '            "type": "fileicon",'
    #echo '            "path": "~/Desktop"'
    #echo '        }'
    echo "}"
  done
  echo ']}'
}

list_by_usage() {
  local list=$(ps -x -o %cpu= -o %mem= -o pid= | sort -nr -k1,1 -k2,2 | head -n $TOP)
  local first=""

  echo '{"items": ['
  echo "$list" | while read cpu mem pid;
  do
    local name=$(ps -p $pid -c -o command=)
    #local bin=$(lsof -p $pid | tr -s ' ' | grep ' txt ' | grep "/$name" | cut -d ' ' -f 9-)
    #local comm=$(ps -p $pid -o comm=)
    local command=$(ps -p $pid -o command=)
    #local len=$(echo $comm | wc -c)
    #local args=$(echo $command | cut -c $len-)

    local uid=$pid
    local title=$name
    local subtitle="$cpu% CPU @ $command"

    if [[ -z "$first" ]];
    then
      first="true"
    else
      echo ","
    fi

    echo "{"
    echo "  \"uid\": \"$uid\","
    echo "  \"title\": \"$title\","
    echo "  \"subtitle\": \"$subtitle\","
    echo "  \"arg\": \"$arg\","
    echo "  \"mods\": {"
    echo "    \"cmd\": {"
    echo "      \"subtitle\": \"Copy pid $pid to clipboard\""
    echo "    },"
    echo "    \"alt\": {"
    echo "      \"subtitle\": \"$subtitle\""
    echo "    }"
    echo "  }"
    #echo '        "autocomplete": "Desktop",'
    #echo '        "icon": {'
    #echo '            "type": "fileicon",'
    #echo '            "path": "~/Desktop"'
    #echo '        }'
    echo "}"
  done
  echo ']}'
}

#
# input: pid
# output: pid
#
grep_id() {
  ps -x -o pid= | grep $1 | while read pid;
  do
    local cpu=$(ps -p $pid -o %cpu=)

    echo $cpu $pid
  done
}

#
# input: name
# output: $cpu $pid
#
grep_name() {
  local name=$1

  pgrep -i $name | while read pid;
  do
    local cpu=$(ps -p $pid -o %cpu=)

    echo $cpu $pid
  done
}

#
# input: port number
# output: $cpu $pid $port
#
grep_port() {
  local prefix=$1

  netstat -anv | grep 'LISTEN' | tr -s ' ' | cut -d ' ' -f 4,9 | grep "\.$prefix" | cut -d '.' -f 2 | uniq | while read port pid;
  do
    local cpu=$(ps -p $pid -o %cpu=)

    echo $cpu $pid $port
  done
}

main() {
  if [ "$QUERY" == ':' ];
  then
    list_by_port_usage
  elif [[ $QUERY =~ :([[:digit:]]+) ]];
  then # match port
    list_by_port ${BASH_REMATCH[1]}
  elif [[ $QUERY =~ [[:digit:]]+ ]];
  then # match id
    list_by_id $BASH_REMATCH
  elif [[ ! -z "$QUERY" ]];
  then # match name
    list_by_name $QUERY
  else
    list_by_usage
  fi
}

main
