gui:
  scrollHeight: 15

  theme:
    activeBorderColor:
      - "#005f87"
      - bold
    inactiveBorderColor:
      - "#c4c4c4"
    selectedLineBgColor:
      - "#e4e4e4"
    inactiveViewSelectedLineBgColor:
      - "#c4c4c4"
