source ~/.config/tmux/theme.conf
source ~/.config/tmux/plugins.conf

set exit-empty off

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-kitty:RGB"
set -g renumber-windows on

set -g base-index 1
set -g mouse on

setw -g mode-keys vi
setw -g clock-mode-style 12

set -g status-interval 5
set -g automatic-rename on
set -g automatic-rename-format '#{b:pane_current_path}'

source ~/.config/tmux/keymap.conf

# TODO kitty image integration
set -gq allow-passthrough on
set -g visual-activity off
set -g focus-events on

run '~/.config/tmux/plugins/tpm/tpm'
