source ~/.config/tmux/theme.conf

set -g pane-border-status off

set exit-empty off


set -g default-command "zsh -l"
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-kitty:RGB"
set -g renumber-windows on

set -g base-index 1
set -g mouse on

setw -g mode-keys vi
setw -g clock-mode-style 12

set -g focus-events on

set-option -g status-interval 5
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

source ~/.config/tmux/keymap.conf
