source ~/.config/tmux/theme.conf

set -g pane-border-status off
#set -g pane-border-status top
#set -g pane-border-format " #{pane_index} #{pane_title} "

set exit-empty off


set -g default-command "zsh -l"
set -g default-terminal "tmux-256color"
#set -g default-shell /opt/homebrew/bin/zsh
set -as terminal-features ",xterm-kitty:RGB"
set -g renumber-windows on

set -g base-index 1
set -g mouse on

setw -g mode-keys vi
setw -g clock-mode-style 12

set -g status-interval 5
set -g automatic-rename on
set -g automatic-rename-format '#{b:pane_current_path}'

source ~/.config/tmux/keymap.conf

# TODO kitty image integration
set -gq allow-passthrough on
set -g visual-activity off
set -g focus-events on
